### ISSUE TITLE
Integer size bug?

### ISSUE THREAD

**Issue by jacobwilliams** [eel3/gccr#1]
When trying to merge two files, I'm getting the following error message:
```
ERROR: cannot parse line 7241 in file json_value_module.F90-no-unicode.gcov
 Is this a valid gcov file?
```
See [here](https://github.com/jacobwilliams/json-fortran/pull/251#issuecomment-277583268) for more details. The [line in question](https://api.travis-ci.org/jobs/198723183/log.txt?deansi=true) seems to be:
```
443233956: 7236:            else if (any(c == control_chars)) then
```
Is it possibly due to the very large integer value for the count (`443233956`)? I don't know anything about perl so I didn't see anything obvious in the code.

**Comment by jacobwilliams** [comment]
Or maybe it's some kind of regex issue not accounting for the number starting in the first column?

**Comment by jacobwilliams** [comment]
The fix is to change:
```perl
    }elsif($line =~ /^\s+(\d+):\s*(\d+):(.*)/) {
```
to:
```perl
    }elsif($line =~ /^\s*(\d+):\s*(\d+):(.*)/) {
```
So that the spaces at the beginning of the line are optional. In this case, there were no spaces. I can submit a pull request for this if you want.

**Comment by eel3** [comment]
Thanks. That's a good suggestion. Could you send me a pull request?

**Comment by zbeekman** [comment]
> Thanks. That's a good suggestion. Could you send me a pull request?

lol kinda lazy but I approve :upside_down_face:
